#+TITLE: Project

* Assumptions
- Can I suppose the proportion of female is independent between 3/2 and 5/2?

* Gather the data
** TODO (list all the URLs)
My progress is summarized in the [[./data_gathering.org][data gathering]] file.

* Manually look at the data
- The html is poorly formatted and difficult to automatically parse.
- The formatting changes from year to year, so I'd better do it carefully and manually parse it year by year.

Take a look, and fix what is fixable.
Then from what is available, remove unusable entries?
Get the statistics of interest.
Then, using the statistics (variation of female percentage throughout the selection process) and ranking of schools / Ecoles, see how the variation of female percentage evolves.
From the top ones, see how it evolves. Same for the low tier schools. (it is an elimination process, so expect a opposite trend).

* Parsing "Lycees" data
Supelec spelling
=TS= --> =TSI= (2002, 2003)
=PS= --> =PSI= (2003, 2004)

=../../data/stat2002/recap_lycee_33.html	2002Banque ENS Cachan/X-ESPCI= --> PSI
=../../data/stat2003/recap_lycee_33_2003.html	2003Banque ENS Cachan/X-ESPCI=
(Cannot be parsed by last word)

2005 and more recent: can know the prepa from the path (directory name)

Remove the =?= in some years (e.g. 2009)

* Logs
** [2021-02-11 Thu]
Start the repo.
Add the raw html data.
The parsing is the ad-hoc boring part. I'll go the quick and dirty way, copy pasting code and "fix it" when it breaks for a specific html to parse.
Some data entries have commas. I'll go with parsing to tsv for now.
Some entries are a summary over the "banque", instead of an Ecole. I can identify them since they begin with a non break space. I make the convention that such an entry will begin with a =¥=, yen symbol, in the parsed file.
Convention:
- Integers are counts
- Decimals are percentages
** [2021-02-27 Sat]
Add the data for 2019's "statistiques generales".
I noticed there are missing data in TSI's number of candidates for Polytechnique.
PT's data also seem to contain missing values.
I also notice that in some years, e.g. 2012, the parsing for a "bank summary" (with the =¥= at the beginning of the line) does not work. I might come back later at this and try to fix it, or just try to identify these lines in another way.

** [2021-11-03 Wed]
Data for lycee is inconsistent. There are lycee with no candidates showing "admissibles", "classes", "integres".
For some other, there are more "admissibles", "classes" or "integres" than "inscrits".
This is true for considering either total number of students, number of males or number of females.
I should also verigy that the number of "inscrits", "asmissibles", "classes" and "integres" is coherent from the statistics by lycee and "stats generales".
