#+TITLE: SCEI statistics

* Question I want to answer
To reduce bias, I state what I want to look at before I start with the analysis as opposed to looking at the data first and then report my findings.
** Main question
Is there a gender difference in the performance at the selective exam "concours grandes écoles d'ingénieurs"?

** Follow ups?
There are other interesting questions:
- Evolution over time of the male / female ratio.
- Evolution over time of the size of the global population.
- Does the male / female ratio correlate with female performance?
- If I do find a gender difference in the performance, does it correlate with the exams' weighting coefficient at the Ecoles? I probably won't answer this one since it takes too much effort to gather the data.
** Explore
I might also report on interesting features I find while looking at the data. If these are not stated above, then these features are things I didn't look for, but stumble upon.

* Data available
A more detailed work in progress summary of what I've done so far is available at [[./project.org][project.org]].
** Broader look
[[https://www.scei-concours.fr/statistiques.php][SCEI (Service concours écoles d’ingénieurs)]] publishes yearly statistics about the results.
Each year, SCEI gives a global statistics about all branches merged.
Each year,for each branch, SCEI gives per Ecole basis statistic. This data is mostly complete, but there are some blanks.
For some years, for some branches, SCEI makes per [[https://en.wikipedia.org/wiki/Classe_pr%C3%A9paratoire_aux_grandes_%C3%A9coles)][CPGE (Classe préparatoire aux grandes écoles)]] data available too.

** More detailed look
From 2004 (included) up to 2017 (included), the rank of the last candidate called is available.
From 2018 onward, median and mean rank of accepted candidates are instead made available.
These data can be used to have an idea of the desirability / selectivity of Ecoles within a school.

* License
The code is licensed under GPL License but the data is © SCEI and was scrapped on February 2021. It is not my property, and it is stored here for archive and research purpose. I will delete it if SCEI asks.
